## Directories
add_subdirectory(testContiguousList)
add_subdirectory(testLinkedList)
add_subdirectory(testLinkedQueue)
add_subdirectory(testLinkedStack)
add_subdirectory(testOpenAddressingHash)
add_subdirectory(testExternalHash)
add_subdirectory(testBinaryTree)
add_subdirectory(testBinaryTreeAsArrays)
add_subdirectory(testAvlTree)
